fint:
  application-id: fint-flyt-case-service
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
spring:
  profiles:
    include:
      - flyt-kafka
      - flyt-logging