fint:
  org-id: fintlabs.no
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    topic:
      org-id: ${fint.org-id}
      domain-context: flyt
    application-id: fint-flyt-case-service
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ${fint.kafka.application-id}
server:
  port: 8083