fint:
  cache:
    defaultCacheEntryTimeToLiveMillis: 518400000
    defaultCacheHeapSize: 1000000
  kafka:
    topic:
      org-id: fintlabs.no
      domain-context: flyt
    application-id: fint-skjema-case-service
spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: fint-skjema-data-service
server:
  port: 8083